name: Build, SonarCloud Analysis and Deploy Docker Image

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Asegúrate de obtener todo el historial de commits

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: sonarcloud  # Este job depende de que el análisis de SonarCloud haya finalizado correctamente.

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Disable CI warnings
        run: |
          echo "CI=false" >> $GITHUB_ENV  # Desactiva el modo estricto de CI para evitar que las advertencias bloqueen el flujo de trabajo.

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t valery2024/cryptopay-frontend:$GITHUB_SHA .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push valery2024/cryptopay-frontend:$GITHUB_SHA
